### ISSUE TITLE
An Easy Way to Print Shift/Reduce Conflicts and Corresponding Rules

### ISSUE THREAD

**Issue by MatthewObi** [alex/rply#113]
I'm debugging the parser and I found shift/reduce conflicts and what states they're from, but I could not find an easy way to print the states and which productions they correspond to. There's no convenient list of states in the LRTable object and there doesn't seem to be an option to emit debug information to a file like [PLY.](https://ply.readthedocs.io/en/latest/ply.html#the-parser-out-file) 

If there's a way around this, it'd be much appreciated.

**Comment by nobodxbodon** [comment]
Have you checked [this solution](https://github.com/alex/rply/issues/28#issuecomment-146506931) for RR conflicts?

**Comment by MatthewObi** [comment]
I did check out the solution. Unfortunately, it wasn't what I was looking for. I did find a solution to my problem (it involved adding some print statements to the code that adds the conflict).
