### ISSUE TITLE
Supporting Python 3.3.5

### ISSUE THREAD

**Issue by b5y** [alex/rply#60]
Hello!

I am on the way to implement 'yield from' ([PEP 380](https://www.python.org/dev/peps/pep-0380/)) construction in [baron](https://github.com/pycqa/baron) project. PyPy supports Python version 3.3.5 and I wonder if rply will support version 3.3.5.

If no one is going to add this in early future, I can try to improve rply.

Best regards,
Mehti

**Comment by alex** [comment]
rply does support python3.3
